### PR TITLE
Updated shared libraries for windows

### PR DESCRIPTION
**Pull request by Zuzu-Typ**
I rebuilt the shared libs for Windows with the latest version of the respective package.
I also built OpenSSL this time, meaning that opusfile has all of it's features enabled.

Using:
flac 1.3.3
libogg 1.3.4
libopusenc 0.2.1
libvorbis 1.3.7
openssl 1.1.1g
opus 1.3.1
opusfile 0.12

### CODE REVIEW

**Comment by mattgwwalker** [comment]
Awesome.  Thanks for that effort :o)  Would you be able to document the process?  It sounds like it's a real pain.  If you're looking for inspiration, you can check out what I wrote for [macOS](https://github.com/TeamPyOgg/PyOgg/blob/master/pyogg/libs/macos/README).

**Comment by Zuzu-Typ** [comment]
> Awesome. Thanks for that effort :o) Would you be able to document the process? It sounds like it's a real pain. If you're looking for inspiration, you can check out what I wrote for [macOS](https://github.com/TeamPyOgg/PyOgg/blob/master/pyogg/libs/macos/README).

I thought about creating a repository with ready-to-buld projects so that it wouldn't require piecing it all together - that would also make it available to other people. I mean it is a popular library.
I can of course try to document it, but I think that such a repo would be much easier to use and maintain.

**Comment by mattgwwalker** [comment]
I think that'd be super useful, but especially for PyOgg whenever there are updates.

**Comment by mattgwwalker** [comment]
Please feel free to merge this if you're ready, it looks great to me.

**Pull request merged**
